language: php
php:
  - 7.2

cache:
  directories:
    - $HOME/.composer/cache

install:
  - cp composer.json.ci ../composer.json
  - cp phpcs.xml.dist ../phpcs.xml.dist
  - cd .. && composer update

script:
  - FLOW_CONTEXT=Testing bin/phpunit -c Build/BuildEssentials/PhpUnit/UnitTests.xml slack/Tests/Unit
  - bin/phpcs slack/Classes